# Generated by Django 5.1.15 on 2026-08-29 17:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='FinCalc', max_length=100)),
                ('site_tagline', models.CharField(default='Free Online Financial & Health Calculators', max_length=255)),
                ('site_description', models.TextField(default='Access free, accurate, and instant financial, business, and health calculators. Mobile-first, transparent formulas, and expert-reviewed tools.')),
                ('contact_email', models.EmailField(blank=True, default='support@fincalc.org', max_length=254)),
                ('google_search_console_id', models.CharField(blank=True, help_text='Google Search Console verification meta tag (e.g. google-site-verification token)', max_length=100)),
                ('google_analytics_id', models.CharField(blank=True, help_text='GA4 Measurement ID (e.g. G-XXXXXXXXXX)', max_length=50)),
                ('copyright_text', models.CharField(default='© 2026 FinCalc. All rights reserved. Calculations are for estimation purposes only.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, help_text='Short subheading below the title', max_length=255)),
                ('intro', models.TextField(blank=True, help_text='Introductory paragraph')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('faq', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('question', 2), ('answer', 3)]], {'icon': 'help'})})),
            ],
            options={
                'verbose_name': 'Standard Page',
                'verbose_name_plural': 'Standard Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
