# Generated by Django 5.1.15 on 2026-08-29 17:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('category_slug_name', models.CharField(help_text='Machine identifier, e.g. finance, health, business', max_length=50)),
                ('icon_name', models.CharField(default='trending-up', help_text='Lucide icon name (e.g. banknote, heart-pulse, briefcase, percent, scale)', max_length=50)),
                ('badge_color', models.CharField(default='blue', help_text='Accent color theme (blue, emerald, violet, amber, rose, cyan)', max_length=50)),
                ('description', models.TextField(help_text='Overview of calculators available in this category for SEO and users.')),
                ('detailed_intro', wagtail.fields.RichTextField(blank=True, help_text='Comprehensive educational introduction establishing topic authority.')),
            ],
            options={
                'verbose_name': 'Category Hub Page',
                'verbose_name_plural': 'Category Hub Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
