# Generated by Django 5.1.15 on 2026-08-29 17:00

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('rich_text', 1), ('faqs', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently Asked Questions'}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('question', 3), ('answer', 1)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('heading', 2), ('items', 5)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(default='Make informed decisions about loans, mortgages, investments, retirement, and health with instant, expert-verified calculation engines.', help_text='Subheading explaining the platform value proposition'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Smart, Accurate & Free Financial Calculators', help_text='Primary H1 headline', max_length=200),
        ),
    ]
